### ISSUE TITLE
AF: version the images used as tool requirements

### ISSUE THREAD

**Issue by martenson** [usegalaxy-au/galaxy-local-tools#20]
AlphaFold tool at https://github.com/usegalaxy-au/galaxy-local-tools/blob/master/tools/alphafold/alphafold.xml#L17 is not versioning its requirements.

```
        <container type="docker">neoformit/alphafold:latest</container>
```

That breaks reproducibility and sometimes also even execution. Consider e.g. a galaxy tool v.1 depending on `neoformit/alphafold:latest` that gets an update to v.2 along with its image. Now all older installations of v1 will automatically use untested image with possibility of breaking changes.

The usual solution to this is to use docker tags and version the images to something like `neoformit/alphafold:v0.0.1` which uniquely pairs the tool with its requirements.

xref https://github.com/usegalaxy-au/galaxy-local-tools/issues/11#issuecomment-1063887789

**Comment by neoformit** [comment]
Thanks @martenson been through so many versions in development I totally overlooked this. Thanks a lot for the feedback, new tag `neoformit/alphafold:v2.1.2_0` is pushed and Toolshed has been updated to match.

**Comment by martenson** [comment]
Thanks for the light speed reaction @neoformit!
