### ISSUE TITLE
[alphafold] data dir is too generic

### ISSUE THREAD

**Issue by gmauro** [usegalaxy-au/galaxy-local-tools#6]
https://github.com/usegalaxy-au/galaxy-local-tools/blob/f51e879c08bbee8de1b1a6ab1f88d27b32005140/tools/alphafold/alphafold.xml#L37
The wrapper supposes to find Alphafold db files into the `/data` path, so the singularity container has to mount the real path to the Alphafold db into that:
`<param id="singularity_volumes">"/data/alphafold_databases:/data:ro,..."</param>`
Unfortunately, Usegalaxy.eu has all data directories starting from /data/...
`<param id="singularity_volumes">"/data/db/:ro,/data/dnb01/galaxy_db/:ro,/data/dnb02/galaxy_db/:ro,/data/dnb03/galaxy_db/:ro,..."</param>`
clashing with the mount point needed now by the wrapper.

I suggest modifying `data_dir` in a more specific string, e.g. `alphafold_db`

**Comment by gmauro** [comment]
ping @GraceAHall

**Comment by bgruening** [comment]
I think this can be closed now.

**Comment by neoformit** [comment]
Resolved by #7 thanks @bgruening
