### ISSUE TITLE
linebreak in sequence input is not allowed in alphafold

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/galaxy-local-tools#9]
Hi,

we got an error report where the tools complains about wrong inputs.

> MSDNGPQNQRNAPRITFGGPSDSTGSNQNGERSGARSKQRRPQGLPNNTASWFTALTQHG__cn__KEDLKFPR

This is a line break that is converted/sanitised by Galaxy. I think this should be allowed and maybe we can use a `configfile` and put the sequence into it, so we do not need to echo it. This way you could also sed all lines with `>` away, before handing it over to alphafold?

**Comment by bgruening** [comment]
The same user has also ask:

> can there be FASTA upload option or userdefined-name possibility as well?

**Comment by neoformit** [comment]
Hey @bgruening thanks for reporting this - we have written a Python validator for the FASTA input so we'll update that to strip out whitespace.
